export const ErrorUSer = {
  SUCCESS: "SUCCESS",
  PASSWORD_ERROR: "PASSWORD_ERROR",
  LOCKED: "LOCKED",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  EMAIL_VERIFY: "EMAIL_NOT_VERIFY",
};
